### PR TITLE
note for binary1230

### PR DESCRIPTION
**Pull request by ItsK1tty**
binary1230, please see this! Need to contact you & need your help. i'm on the last step from saving WebDisplays

### CODE REVIEW

**Comment by ItsK1tty** [comment]
Sigh. Anyway, I'm having trouble compiling MCEF (montoyo/mcef) with a new, custom JCEF that is compiled with proprietary codecs. Mind giving me a hand? [jcef](https://files.catbox.moe/bnsxu3.zip).
Montoyo's not answering, and you're the only one who actually tried doing something.

**Comment by binary1230** [comment]
Sorry I mistook your pull request for spam. Can you verify you are not a bot?

Anyway

It's been forever since I looked at this, I managed to get stuff working a long time ago but I basically forgot everything involved. I basically did just enough to get it working again on my setup

All of this stuff is really brittle and fragile, and there have been upstream changes that I haven't looked at since I worked on this.  I don't think I'm going to be too helpful. If you have a specific question maybe I can help with that but mostly it's just about poking at it until it works.

**Comment by ItsK1tty** [comment]
> Can you verify you are not a bot?

изображение
~~If you look at my profile at least once, you can see it's full of activity at /webdisplays.~~ nevermind, github doesn't log issue answers.
 I'm currently trying to resolve compilation errors by decompiling jcef's JARs and comparing it, but, eh, I'm already out of ideas.
I don't really understand the errors I get, because I have near-zero Java knowledge, so I'm just googling & hoping. I'll provide everything I've got by now, if you're in.

**Comment by binary1230** [comment]
Hahah. OK I believe you : ) Sorry, been getting lots of spam lately.

I took another look at this, starting to vaguely remember stuff, I'm pretty fuzzy from 2 years ago.

Here's my suggestion, but, it might be stuff you already tried?

https://github.com/montoyo/mcef/pull/31 this is a PR where I was trying to merge changes from a different version of JCEF into Montoyo's code.  I left a ton of comments in there as breadcrumbs in case I ever had to do that again.

The whole thing is an exercise in frustrating merging.  If that's the wall you're running into, maybe try this strategy:

1. Find the unmodified version of JCEF that Montoyo is using, commit that into a new git repo and call that branch "upstream"
2. Paste Montoyo's JCEF modifications on top of that as a new commit, commit as-is, call that branch "MCEF".
3. Go back to the "upstream" branch, and paste your CEF Java code on top of it.  Commit and call that branch "upstream-update"
4. Do a rebase from "MCEF" branch onto "upstream-update", and see if that helps make better sense of the merging

The idea behind that is, might make it easier to spot what the differences are from old CEF->Montoyo CEF mods    vs new CEF  vs old CEF. Could make diagnosing what's going wrong easier.

Also,

The other tip I have is, you can test the MCEF mod without the WebDisplays mod by pressing F10, it'll show a window that is a 2d web browser. if that's working, then MCEF is working. it's a handy way to troubleshoot whether something is an MCEF mod problem vs WebDisplays mod problem.

--

Otherwise if you have other questions throw them in here I'll answer as best I can.  I remember this upgrade being an exercise in just banging on the code until it somehow actually started working again. 

I wonder if there are newer ways to do some of this, like, maybe streaming just streaming a video stream into minecraft and proxying mouse clicks out, so the web browser complexity part of this is abstracted away? I need to look at it again someday.  Anyway, Good luck!

**Comment by ItsK1tty** [comment]
> I wonder if there are newer ways to do some of this, like, maybe streaming just streaming a video stream into minecraft and proxying mouse clicks out, so the web browser complexity part of this is abstracted away? I need to look at it again someday. Anyway, Good luck!

The point of the mod was (and is) to bring the browser into the Minecraft (that's why there's a `web` in the name), but the other option is to get VLC into minecraft in order to play media, as people suggested in before (won't find the issue now). I'll try that strategy, but I have a feeling that we need @montoyo here anyway

**Comment by ItsK1tty** [comment]
I think I got to something. I've resolved dependencies errors, but now it tells me something magical that I have no clue in:
[gradle.log](https://github.com/binary1230/mcef/files/5997707/gradle.log)

**Comment by ItsK1tty** [comment]
Still no response from Montoyo in any way, been a month already. Strange - he's active in private repo's.

**Comment by ItsK1tty** [comment]
Reduced the error amount to 10, most of them are about converting IBrowser data type to the CefBrowserOsr and back. Can we work something out?

**Pull request closed without merging**
